
services:
  - type: web
    name: horlapookie-bot
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_PREFIX
        sync: false
        generateValue: false
      - key: BOT_OWNER
        sync: false
        generateValue: false
      - key: BOT_NAME
        value: HORLA POOKIE Bot
      - key: BOT_SESSION_DATA
        sync: false
        generateValue: false
      - key: TEST_MODE_ONLY
        value: false
      - key: VIPS_WARNING
        value: "0"
      - key: OPENAI_API_KEY
        sync: false
        generateValue: false
      - key: GEMINI_API_KEY
        sync: false
        generateValue: false
    autoDeploy: true
    healthCheckPath: /
