services:
  - type: web
    name: horlapookie-bot
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_PREFIX
        value: .
      - key: TEST_MODE_ONLY
        value: false
      - key: VIPS_WARNING
        value: "0"
    autoDeploy: true
