services:
  - type: web
    name: horlapookie-bot
    runtime: node
    region: oregon
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y \
        libglib2.0-0 \
        libnss3 \
        libatk1.0-0 \
        libatk-bridge2.0-0 \
        libcups2 \
        libdrm2 \
        libxkbcommon0 \
        libxcomposite1 \
        libxdamage1 \
        libxfixes3 \
        libxrandr2 \
        libgbm1 \
        libasound2 \
        libpango-1.0-0 \
        libcairo2 \
        ffmpeg \
        libvips42 && \
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_PREFIX
        value: .
      - key: TEST_MODE_ONLY
        value: false
    autoDeploy: true
